name: Generate Datas

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Clona o repositório
      - uses: actions/checkout@v3

      # Cria a pasta dist (garante que exista)
      - name: Create dist folder
        run: mkdir -p dist

      # Gera a cobrinha
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: pedrohsantanaa
          outputs: |
            dist/github-contribution-grid-snake.svg

      # Lista arquivos (debug)
      - name: List contents of dist
        run: ls -la dist

      # Faz o deploy da cobrinha para o branch output
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
